# This is a basic workflow to help you get started with Actions
######## 记得把dockerfile中的这一行“&& sed -i 's#http://deb.debian.org#http://mirrors.aliyun.com/#g' /etc/apt/sources.list\”删掉

name: Build Docker Image 
# Controls when the action will run.
on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
# Allows you to run this workflow manually from the Actions tab
# 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: lixaster/electricity-tracker
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_TOKEN }}'
          tags: "latest,v0.0.1"
